name: sis
services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - sis_network
    volumes:
      - sis_data:/data/db

  server:
    image: ghcr.io/mezeipetister/sis_server:latest
    build:
      context: ../server
      dockerfile: Dockerfile
      # args:
        # - SERVICE_NAME=login_service
    restart: always
    env_file:
      - ENV.list
    networks:
      - sis_network
    depends_on:
      mongo:
        condition: service_started
  web_gui:
    image: ghcr.io/mezeipetister/sis_web:latest
    build:
      context: ../web
      dockerfile: Dockerfile
    volumes:
      - ../web:/app
    restart: always
    ports:
      - "3200:3000"
    env_file:
      - ENV.list
    networks:
      - sis_network
    depends_on:
      mongo:
        condition: service_started

networks:
  sis_network:
    driver: bridge

volumes:
  sis_data:
